### ISSUE TITLE
API: dashboard/subject

### ISSUE THREAD

**Issue by abglnv** [anyrange/enis2#33]
```
{"message":"Время работы с модулем завершено. Для продолжения пожалуйста обновите модуль."}
```
I tried sending requests through swagger and automating them with code (I thought I was doing it too slowly myself), but nothing changed. How to get response status 200?

**Comment by thaseyor** [comment]
Looks like misuse of evalutations. I am currently unable to check the problem, but you can try to observe requests sent by web client.
However, I would highly recommend you to look into new nis api used for mobile app (micros.nis.edu.kz), although its not documented anywhere as well, it is much more stable and easier to use than sms api, hence does not require broker like our api. 
If you have any questions feel free to reach out to me in telegram
